version: '3.1'
services:
  wordpress:
    image: wordpress
    #this specifies that wordpress is dependend on mysql, so before building wordpress, build mysql.
    depends_on:        
      - mysql             
    ports:
      - '80:80'
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_NAME=exampledb
      - WORDPRESS_DB_PASSWORD=examplepass
    #volumes helps to save all data locally, so if the container crashes or something the data is still available in local storage.
    #volumes:      
      #- ./wordpress:/var/www/html
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
      #root password should be mentioned to launch the content
      - MYSQL_RANDOM_ROOT_PASSWORD='1'      
    #volumes:
      #- ./mysql:/var/lib/mysql

