name: deploy to AWS EB
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: login to docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: build the image
        run: docker-compose build -p sreeram91/wordpress-mysql -f ./docker-compose.yaml build
      
      - name: push to hub
        run: docker-compose push sreeram91/wordpress-mysql

      